# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sample.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class SearchRequest(betterproto.Message):
    query: str = betterproto.string_field(1)
    page_number: int = betterproto.int32_field(2)
    results_per_page: int = betterproto.int32_field(3)
